import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import DarkModeToggle from "@/components/DarkModeToggle";
import { Navbar } from "@/components/Navbar";
import { ClientProvider } from "./ClientProvider";
import { store } from "@/store/store";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <head />
      <body>
        <ClientProvider>
          <ThemeProvider attribute="class">
            {/* <DarkModeToggle /> */}
            <Navbar />
            {children}
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
